version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:4000
      - REACT_APP_WS_URL=ws://localhost:4000
    depends_on:
      - backend
    networks:
      - datachain-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/datachain
      - REDIS_URL=redis://redis:6379
      - AI_ENGINE_URL=http://ai-engine:5000
      - JWT_SECRET=your_jwt_secret_key_for_development
      - SOLANA_RPC_URL=https://api.devnet.solana.com
    depends_on:
      - db
      - redis
      - ai-engine
    networks:
      - datachain-network

  ai-engine:
    build:
      context: ./ai-engine
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./ai-engine:/app
      - ./ai-engine/models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_CACHE_DIR=/app/models
      - LOG_LEVEL=INFO
    networks:
      - datachain-network

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=datachain
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - datachain-network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - datachain-network

  solana-validator:
    image: solanalabs/solana:stable
    ports:
      - "8899:8899"
      - "8900:8900"
    command: solana-test-validator
    volumes:
      - solana-test-ledger:/root/.local/share/solana/test-ledger
    networks:
      - datachain-network

networks:
  datachain-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  solana-test-ledger: 